modLoader="javafml"
loaderVersion="[24,]"
issueTrackerURL="http://zyyaruzi.com/"
license="LGPL v2.1"

[[mods]]
modId="zyyserver"
displayName="zyyserverMod"
authors="Zyy"
version="1.0.0-dev"
credits="ğŸ¤¡"
description='''
    èœé¸¡æ²¡æœ‰æè¿°
    '''