modLoader="javafml"
loaderVersion="[24,]"
issueTrackerURL="http://zyyaruzi.com/"
logoFile="logo.png"
license="LGPL v2.1"

[[mods]]
modId="zyyloader"
displayName="ZyyLoader"
authors="Zyy"
# We use the global forge version
version="1.0.0-dev"
credits="ğŸ¤¡"
description='''
    èœé¸¡æ²¡æœ‰æè¿°
    '''
