modLoader="javafml"
loaderVersion="[36,]"
issueTrackerURL="http://zyyaruzi.com/"
logoFile="logo.png"
license="LGPL v2.1"

[[mods]]
modId="zyyserver"
displayName="zyyserver"
authors="Zyy"
version="1.0.0-dev"
credits="ğŸ¤¡"
description='''
    èœé¸¡æ²¡æœ‰æè¿°
    '''